# ベースイメージとしてNode.jsの公式イメージを使用
FROM node:14-alpine

# 作業ディレクトリを設定
WORKDIR /app

# パッケージファイルをコピー
COPY package.json package-lock.json ./

# 依存関係をインストール
RUN npm install

# アプリケーションのソースコードをコピー
COPY . .

EXPOSE 3000

CMD ["npm", "start"]