# ベースイメージとしてNode.jsの公式イメージを使用
FROM node:14-alpine

# 作業ディレクトリを設定
WORKDIR /app

# パッケージファイルをコピー
COPY package.json package-lock.json ./

# 依存関係をインストール
RUN npm install && \
    npm install -D tailwindcss@3.3.3 postcss@8.4.28 autoprefixer@10.4.15 @babel/plugin-proposal-private-property-in-object@7.21.11 && \
    npm install js-cookie react-big-calendar moment

# アプリケーションのソースコードをコピー
COPY . .

# Tailwind CSSの設定ファイルを生成
RUN npx tailwindcss init -p

EXPOSE 3000

# アプリケーションを起動
CMD ["npm", "start"]